from groq import Groq

# custom imports
from models.models import *

def count_alphanumeric(name: str) -> int:
    count = 0
    for character in name:
        if character.isalnum():
            count += 1
    return count


# def llm_content_check(receipt: ReceiptRequest) -> bool:
#     client = Groq(api_key="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")

#     chat_completion = client.chat.completions.create(
#         messages=[
#             {
#                 "role": "system",
#                 "content": "You are an assistant helping to determine whether the store receipts given to you are LLM generated or not"
#             },
#             {
#                 "role": "user",
#                 "content": f"Consider the following receipt: {receipt.__str__}. Is this generated by a LLM? Please answer only as Yes or No",
#             }
#         ],
#         model="llama-3.3-70b-versatile",
#         temperature=0.1,
#         max_completion_tokens=10,
#         top_p=1,
#         stop="end",
#         stream=False
#     )
 
#     llm_generated_output = chat_completion.choices[0].message.content

#     if llm_generated_output.lower() == "yes":
#         return True
#     else:
#         return False